### ISSUE TITLE
Sugestão de mudança na ordenação. 

### ISSUE THREAD

**Issue by Luismijias** [netuno-org/platform#1]
Gostaria de sugerir um mudança na ordenacão dos itens, tipos, estados, Funcionalidades e etc. Quando entramos na página para procurar determindo item tenho sempre que clicar sobre a ordem para ficar descrescente, gostaria que isso se tornasse padrão, ao invés dos IDs como está hoje. Uma outra idéia mais elaborada seria criar um "state" para que o ultimo modo de  ordenação que eu escolher permanecesse assim que voltasse à funcionalidade.Obrigado e bom trabalho à todos ;-) .

**Comment by eduveks** [comment]
Olá Luís,

Está melhoria foi implementada e está disponível na versão de teste:

- https://github.com/netuno-org/platform/releases/tag/testing

Abraço
