### ISSUE TITLE
Histórico de Querys

### ISSUE THREAD

**Issue by Luismijias** [netuno-org/platform#3]
Uma melhoria que gostaria que fosse implementada seria salvar nossas Querys para futuras consultas ou até mesmo que elas não se apagassem após deslogar do netuno somente com um botão clear pois as vezes precisamos de fazer melhorias e temos que escrevelas novamente.Qualquer uma das opções estaria de bom tamanho.Obrigado.

**Comment by eduveks** [comment]
Está feito e já disponível na versão de teste atual.
Muito obrigado.

**Comment by Luismijias** [comment]
Muito bom, para quem não está habitualmente fazendo querys será muito útil.
